@echo off
echo Running all GSL test programs now...
echo.

echo Starting test-block...
test-block
echo.
echo Starting test-bspline...
test-bspline
echo.
echo Starting test-bst...
test-bst
echo.
echo Starting test-cblas...
test-cblas
echo.
echo Starting test-cdf...
test-cdf
echo.
echo Starting test-cheb...
test-cheb
echo.
echo Starting test-combination...
test-combination
echo.
echo Starting test-complex...
test-complex
echo.
echo Starting test-deriv...
test-deriv
echo.
echo Starting test-dht...
test-dht
echo.
echo Starting test-diff...
test-diff
echo.
echo Starting test-eigen...
test-eigen
echo.
echo Starting test-err...
test-err
echo.
echo Starting test-fft...
test-fft
echo.
echo Starting test-filter...
test-filter
echo.
echo Starting test-fit...
test-fit
echo.
echo Starting test-histogram...
test-histogram
echo.
echo Starting test-ieee-utils...
test-ieee-utils
echo.
echo Starting test-integration...
test-integration
echo.
echo Starting test-interpolation...
test-interpolation
echo.
echo Starting test-linalg...
test-linalg
echo.
echo Starting test-matrix...
test-matrix
echo.
echo Starting test-min...
test-min
echo.
echo Starting test-monte...
test-monte
echo.
echo Starting test-movstat...
test-movstat
echo.
echo Starting test-multifit...
test-multifit
echo.
echo Starting test-multifit_nlinear...
test-multifit_nlinear
echo.
echo Starting test-multilarge...
test-multilarge
echo.
echo Starting test-multilarge_nlinear...
test-multilarge_nlinear
echo.
echo Starting test-multimin...
test-multimin
echo.
echo Starting test-multiroots...
test-multiroots
echo.
echo Starting test-multiset...
test-multiset
echo.
echo Starting test-ntuple...
test-ntuple
echo.
echo Starting test-ode-initval...
test-ode-initval
echo.
echo Starting test-ode-initval2...
test-ode-initval2
echo.
echo Starting test-permutation...
test-permutation
echo.
echo Starting test-poly...
test-poly
echo.
echo Starting test-qrng...
test-qrng
echo.
echo Starting test-randist...
test-randist
echo.
echo Starting test-rng...
test-rng
echo.
echo Starting test-roots...
test-roots
echo.
echo Starting test-rstat...
test-rstat
echo.
echo Starting test-siman...
test-siman
echo.
echo Starting test-sort...
test-sort
echo.
echo Starting test-spblas...
test-spblas
echo.
echo Starting test-specfunc...
test-specfunc
echo.
echo Starting test-splinalg...
test-splinalg
echo.
echo Starting test-spmatrix...
test-spmatrix
echo.
echo Starting test-statistics...
test-statistics
echo.
echo Starting test-sum...
test-sum
echo.
echo Starting test-sys...
test-sys
echo.
echo Starting test-vector...
test-vector
echo.
echo Starting test-wavelet...
test-wavelet
echo.

pause
